[project]
name = "panel-reactflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "panel>=1.7.5",
    "watchfiles>=1.1.0",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
